name: Deploy Hexo Blog

on:
  push:
    branches:
      - main # 监听 main 分支的推送事件

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 初始化子模块
    - name: Initialize submodules
      run: git submodule update --init --recursive

    # 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Hexo 推荐使用 Node.js 16

    # 进入 hexo 目录
    - name: Change directory to hexo
      run: cd hexo

    # 安装依赖
    - name: Install dependencies
      run: |
        cd hexo
        npm install

    # 生成静态文件
    - name: Build Hexo
      run: |
        cd hexo
        npx hexo generate

    # 在生成静态文件后添加
    - name: Disable Jekyll
      run: touch ./hexo/public/.nojekyll

    # 部署到 gh-pages 分支
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./hexo/public